### ISSUE TITLE
Tarifa 3.0TD

### ISSUE THREAD

**Issue by Patrick010** [MiguelAngelLV/tarifa_20td#10]
Sea posible de modificar esta integracion para utilizarla con Tarifa 3.0TD?

**Comment by MiguelAngelLV** [comment]
Entiendo que no sería complejo crear una versiń modificada (un fork), sería cuestión de aceptar 6 parámetros precios y en el actualizar comprobar, además de las horas, los meses.

A poco que le eches un rato supongo que podrías adaptarla.

**Comment by MiguelAngelLV** [comment]
Quizás en un futuro me podría plantear añadirla a esta integración, pero ahora mismo tengo varias cosas en pendientes.

**Comment by MiguelAngelLV** [comment]
Finalmente añadiré en una próxima versión la tarifa 3.0 TD también, para que quede todo juntito.

**Comment by marioJR1979** [comment]
Yo lo estoy usando con una 3.0 pero con lo precios indexados. Lo hago sumando al precio PVPC por hora el margen por Kwh que me puso la comercilizadora que en mi caso es de 0,005 €/Kwh.

Pero tengo problemas con el fijo ya que lo estoy haciendo con 2 instalaciones y en una tengo 80 Kw por periodo y en otra 42 Kw de potencia en el periodo más grande. El caso es que por día entre las dos me sale algo mas de 12 € y como solo est puesto de máximo 10 € pues me quedo corto. ¿Te importaría, Miguel, elevar el máximo díario de 10 € a 15 €?

Gracias.

Un saludo.

**Comment by MiguelAngelLV** [comment]
Lo apunto para la siguiente actualización

**Comment by marioJR1979** [comment]
Una cosa, aclarar para Patrick, pongo el margen de 0.005€ en Tarifa 2.0TD en cada periodo, y con un ayudante, le sumo al precio PVPC. Luego en el panel de energía utilizo esa entidad como valor de precio.

Un saludo.

**Comment by MiguelAngelLV** [comment]
Cerrado en #17
