### ISSUE TITLE
Cambio de version de holidays==0.18.0

### ISSUE THREAD

**Issue by SrBurner** [MiguelAngelLV/tarifa_20td#11]
Hola, hoy he actualizado HomeAssistant a la version 2023.12.3 y me ha dejado de funcionar la integración Dia Laborable (Workday) la he desinstalado a vuelto a instalar y me marcaba error. Finalmente he trazado la incidencia hasta esta integración, y la he parcheado aumentando la version de (“holidays==0.18.0”) a (“holidays==0.38”) en el manifest y reiniciando Home Assistant. Por lo que deduzco que es necesario realizar una actualización a dicha dependencia.

**Comment by MiguelAngelLV** [comment]
La actualizo.

**Comment by SrBurner** [comment]
Muchas gracias y que velocidad!

**Comment by MiguelAngelLV** [comment]
Pues la he estado probado un rato y ya funciona correctamente.

He puesto que la versión sea >= 0.18, así no volverá a fallar en caso de que suban de nuevo la versión del workday.

**Comment by javifly** [comment]
Me ha pasado igual después de la actualización la integración dejo de funcionar. No sabia a que se debía pero al leer que es generalizado pues mira... ahora lo entiendo. van a sacar update corrigiéndolo?
