### ISSUE TITLE
Aviso Will Be Depecrated

### ISSUE THREAD

**Issue by SrBurner** [MiguelAngelLV/tarifa_20td#12]
Al iniciar Home Assistant aparecen varios avisos en los LOGS:

DEVICE_CLASS_MONETARY was used from tarifa_20td, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.MONETARY instead, please create a bug report at https://github.com/MiguelAngelLV/tarifa_20td/issues

STATE_CLASS_TOTAL_INCREASING was used from tarifa_20td, this is a deprecated constant which will be removed in HA Core 2025.1. Use 
SensorStateClass.TOTAL_INCREASING instead, please create a bug report at https://github.com/MiguelAngelLV/tarifa_20td/issues

DEVICE_CLASS_ENERGY was used from tarifa_20td, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.ENERGY instead, please create a bug report at https://github.com/MiguelAngelLV/tarifa_20td/issues

Entiendo que simplemente es que han cambiado la nomenclatura de las variables y es necesario adaptarlas antes de 2025.

**Comment by javifly** [comment]
Si, yo entiendo lo mismo con los mensajes que aquí nos pones. A mi aún no me han salido, que versión de HA tienes tu? la ultima de febrero 2024?

**Comment by MiguelAngelLV** [comment]
>Entiendo que simplemente es que han cambiado la nomenclatura de las variables y es necesario adaptarlas antes de 2025.

Correcto, todavía tengo tiempo de sobra. Estoy haciendo una limpieza de código bien hermosa que incluye esta corrección. El problema es que llevo 3 semanas de obra en casa y «no me da la vida».

**Comment by javifly** [comment]
vas sobrado de tiempo, atiende bien la obra que siempre hay que estar encima de ellas... que después quedan como quedan. Seguro que es cuestión de unas semanas y luego ya saques nuevas versión corregida. Hasta 2025 aun queda y me da que no te pillaremos con las uvas en la mano programando el cambio... :_)

**Comment by SrBurner** [comment]
> Si, yo entiendo lo mismo con los mensajes que aquí nos pones. A mi aún no me han salido, que versión de HA tienes tu? la ultima de febrero 2024?

Si, tengo la version 2024.2.1 hay margen de sobra, solo lo he escrito para avisar.

**Comment by MiguelAngelLV** [comment]
Cerrado en #17
