### ISSUE TITLE
Bug cuando creas dos instancias

### ISSUE THREAD

**Issue by victorcpascua** [MiguelAngelLV/tarifa_20td#14]
Cuando creas una segunda instancia en la segunda no aparecen las entidades.

(En mi caso quería usarlo para trackear solo los costes fijos de un segundo contador)

![image](https://github.com/MiguelAngelLV/tarifa_20td/assets/39152749/7446f62d-2b61-4666-9eb7-0481bc90a672)

**Comment by MiguelAngelLV** [comment]
La verdad es que no estaba pensado para funcionar con dos instancias, pero lo apunto para la siguiente versión

**Comment by MiguelAngelLV** [comment]
Cerrado en #17
