### ISSUE TITLE
[FEATURE REQUEST] Obtener kW gastados por periodo

### ISSUE THREAD

**Issue by victorcpascua** [MiguelAngelLV/tarifa_20td#15]
Estaría bien poder tener los consumos por cada periodo.

**Comment by MiguelAngelLV** [comment]
Desgraciadamente esa característica excede el propósito del componente. 

Ya se comentó en esta ISSUE y se dió una solución alternativa: https://github.com/MiguelAngelLV/tarifa_20td/issues/6
