### ISSUE TITLE
Duda IVA e impuesto eléctrico

### ISSUE THREAD

**Issue by Polosaz** [MiguelAngelLV/tarifa_20td#16]
Más que un Issue quería preguntar una duda. ¿La integración añade automáticamente el IVA y el impuesto eléctrico al precio de la energía y a los costes fijos que pongamos? ¿o no lo considera y deberíamos meter los precios ya con los impuestos incluidos?

**Comment by MiguelAngelLV** [comment]
La integración no calcula nada de eso. Tendrás que sumárselos tú a los valores que introduzcas o tenerlos en cuanta a la hora de ver el resultado final.

Realmente depende de cada caso, porque por ejemplo si tienes panales solares los excedentes se descuentan antes de aplicar los impuests.
