### ISSUE TITLE
No aparece el sensor para seleccionar 

### ISSUE THREAD

**Issue by chacal525** [MiguelAngelLV/tarifa_20td#21]
Para configurar el sensor de seguimiento en el apartado "
Usar una entidad que realiza un seguimiento de los costes totales"  no puedo seleccionar el sensor precio, en cambio si aparecen los de costes totales. Bug o algo que esté haciendo mal?

**Comment by MiguelAngelLV** [comment]
Para el precio por kWh tienes que seleccionar la opción de precio actual, la de totales es para la parte fija.

**Comment by chacal525** [comment]
Lo sé pero no la puedo seleccionar porque no da la opción

**Comment by chacal525** [comment]
Perdona, me había liado, ya funciona todo, gracias
