### ISSUE TITLE
Detected blocking call to import_module inside the event loop

### ISSUE THREAD

**Issue by ellull** [MiguelAngelLV/tarifa_20td#22]
Buenos días,

Lo primero, darte las gracias por esta integración. La verdad es que ayuda a calcular en home assistant unos costes muy parecidos a la realidad si vivies en España.

Pero te creo este issue porque acabo de ver el siguiente mensaje en los logs de mi Home Assistant:

> Logger: homeassistant.util.loop
> Source: util/loop.py:99
> First occurred: May 23, 2024 at 15:44:37 (1 occurrences)
> Last logged: May 23, 2024 at 15:44:37
> 
> Detected blocking call to import_module inside the event loop by custom integration 'tarifa_20td' at custom_components/tarifa_20td/sensor.py, line 81: Tariff20TD(p1, p2, p3) (offender: /usr/local/lib/python3.12/site-packages/holidays/registry.py, line 224: self.entity = getattr(importlib.import_module(self.module_name), self.entity_name)), please create a bug report at https://github.com/MiguelAngelLV/tarifa_20td/issues

Recientemente he visto issues similares a esta resueltas en los changelogs de varias integraciones así que sospecho que se debe a algún cambio que se ha hecho en versiones recientes de Home Assistant.

**Comment by MiguelAngelLV** [comment]
Sí, parece que es algún cambio que habrán añadido en las últimas versiones. En cuanto pueda le echo un vistazo. no tiene pinta de ser muy algo complejo.

Gracias por el aviso.

**Comment by BelenCaSa** [comment]
A mi me aparece este error

Registrador: homeassistant.util.loop
Fuente: util/loop.py:84
Ocurrió por primera vez: 02:32:58 (1 ocurrencias)
Último inicio de sesión: 02:32:58

Detected blocking call to import_module inside the event loop by custom integration 'tarifa_20td' at custom_components/tarifa_20td/sensor.py, line 81: Tariff20TD(p1, p2, p3) (offender: /usr/local/lib/python3.12/site-packages/holidays/registry.py, line 236: self.entity = getattr(importlib.import_module(self.module_name), self.entity_name)), please create a bug report at https://github.com/MiguelAngelLV/tarifa_20td/issues Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/tarifa_20td/__init__.py", line 34, in async_setup_entry await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2032, in async_forward_entry_setups await asyncio.gather( File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2034, in <genexpr> create_eager_task( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2081, in _async_forward_entry_setup await entry.async_setup(self.hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup result = await component.async_setup_entry(hass, self) File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 134, in async_setup_entry return await component.async_setup_entry(entry) File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 196, in async_setup_entry return await self._platforms[key].async_setup_entry(config_entry) File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 333, in async_setup_entry return await self._async_setup_platform(async_create_setup_awaitable) File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 363, in _async_setup_platform awaitable = create_eager_task(awaitable, loop=hass.loop) File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/config/custom_components/tarifa_20td/sensor.py", line 81, in async_setup_entry Tariff20TD(p1, p2, p3)
