### ISSUE TITLE
No se instala desde el gestor de integraciones

### ISSUE THREAD

**Issue by xavi4** [MiguelAngelLV/tarifa_20td#3]
Se queda colgado en el asistente de configuracion. No se acaba de instalar.

**Comment by MiguelAngelLV** [comment]
¿Podrías dar más datos?

¿O poner alguna captura?

**Comment by MiguelAngelLV** [comment]
Lo he probado en una instalación limpia con la última versión de HA y funciona correctamente aunque si es cierto que ha tardado como un minuto instalando cosas antes de mostrar el asistente.

**Comment by xavi4** [comment]
Hola Miguel Angel,
Adjunto captura de pantalla.

Saludos y disculpa.

**Comment by MiguelAngelLV** [comment]
No se ha adjuntado a imagen. Mejor responde desde el propio Github.

**Comment by xavi4** [comment]
![Screenshot_20230917_151508_Home Assistant~2](https://github.com/MiguelAngelLV/tarifa_20td/assets/10924997/ac0c0146-0163-434e-b221-fec3b2b7c2a5)
![Screenshot_20230917_152151_Home Assistant~2](https://github.com/MiguelAngelLV/tarifa_20td/assets/10924997/446b8f30-2fbe-41a1-99f2-dcbdd719baaf)

**Comment by MiguelAngelLV** [comment]
Ese error no parece venir del componente en sí, sino de HA.

¿Podrías mirar los registros de HA a ver si aparece algún error?

**Comment by xavi4** [comment]
Tenías razón, Miguel Ángel. Perdona por la molestia ocasionada. Lo he solucionado desinstalando la integración de Tapo  y una de Raspberry pi GPIO, lo que creaba inestabilidad en el sistema. Disculpa y mil gracias.
