### ISSUE TITLE
Tarifas con 2 tramos y precios excedentes.

### ISSUE THREAD

**Issue by amzaldua** [MiguelAngelLV/tarifa_20td#4]
Hola Miguél,

Quería aprovechar para felicitarte por el componente de balance neto, al final he optado por utilizarlo reemplazando los cálculos en template ya que tiene un comportamiento mas estable.

Sobre este componente, el de tarifas 2.0TD, en mi caso:
-. Tengo únicamente 2 tramos.
-. No veo donde definir el precio de los excedentes.
-. Seria necesario concretar los horarios de las tarifas.
La potencia importada ya la tengo disgregada en 2 tramos por tenerlo un poco mas controlado y porque hace tiempo hice una aproximación y se me calentó mucho la cabeza y terminé por apartarlo momentáneamente. Luego esta el tema de que por muchos excedentes que tengas nunca van a abonarte dinero, la batería virtual, el máximo que pueden descontarte. Si todavía tienes paciencia conmigo puedo servirte de betatester. :)
Te adjunto una captura de mi factura.
<img width="972" alt="Captura de pantalla 2023-09-19 a las 1 14 07" src="https://github.com/MiguelAngelLV/tarifa_20td/assets/116205677/c52902d7-88b4-482b-9cf3-5670888d7c47">

Un saludo.

**Comment by MiguelAngelLV** [comment]
Buenas.

>-. Tengo únicamente 2 tramos.
Este componente está diseñado para Tarifas 2.0 TD, y la tarifa que tienes no es 2.0 TD, pues tiene solo 2 tramos y no coincide con los tramos de esta tarifa.

La idea de este componente es crear un entidad cuyo valor va cambiando según la hora del día para indicar el precio de dicha hora. Lógicamente, estos tramos no coincidirán con los tuyos, entre otras cosas, porque los fines de semana siempre los considera valle por ejemplo.

>-. No veo donde definir el precio de los excedentes.
Hasta ahora no he visto ninguna tarifa que tenga excedentes por tramos. O bien son fijos (como es tu caso) o se basan en PVPC.
Para los que tenemos excedentes fijos, basta en indicarlo en el panel de control de Energía. Tener una entidad que simplemente marque un valor fijo todo el rato no aporta nada.

>-. Seria necesario concretar los horarios de las tarifas.
Los horarios son los oficiales Tarifa 2.0 TD 

![image](https://github.com/MiguelAngelLV/tarifa_20td/assets/638110/59fe1caa-d838-4ee4-b38e-efda7a743972)


>La potencia importada ya la tengo disgregada en 2 tramos por tenerlo un poco mas controlado y porque hace tiempo hice una aproximación y se me calentó mucho la cabeza y terminé por apartarlo momentáneamente. 

Esto no influye en el componente. Al componente lo único que le interesa el precio fijo diario (incluyendo las dos potencias, alquileres...) 

>Luego esta el tema de que por muchos excedentes que tengas nunca van a abonarte dinero, la batería virtual, el máximo que pueden descontarte

Esto es algo que queda fuera del ámbito del componente. En todo caso, sería crear un nuevo componente para generar facturas dónde tenga en cuenta los límites.

En mi caso, con Octopus, como no tengo límite, lo único que consigo es que el resultado al final del mes es «negativo», pero que yo interpreto como dinero hacia la hucha.

![image](https://github.com/MiguelAngelLV/tarifa_20td/assets/638110/2f3c5400-66d1-4866-9bcc-8588abcba982)

**Comment by amzaldua** [comment]
>Este componente está diseñado para Tarifas 2.0 TD, y la tarifa que tienes no es 2.0 TD, pues tiene solo 2 tramos y no coincide con los tramos de esta tarifa.

Aquí discrepo porque mi tarifa, al menos según la comercializadora, es 2.0TD.:

<img width="333" alt="Captura de pantalla 2023-09-19 a las 9 34 14" src="https://github.com/MiguelAngelLV/tarifa_20td/assets/116205677/b6000edd-6ecf-47c4-ba58-a1276eb09aa5">

>La idea de este componente es crear un entidad cuyo valor va cambiando según la hora del día para indicar el precio de dicha hora. Lógicamente, estos tramos no coincidirán con los tuyos, entre otras cosas, porque los fines de semana siempre los considera valle por ejemplo.

De acuerdo, entonces creo que tenia otra idea yo en la cabeza con respecto al componente.
De cualquier manera gracias, me has dado un par de ideas sobre como ser mas preciso en el calculo de precios. ¿Mi objetivo? De igual manera que veo minuto minuto y por electrodoméstico el consumo en energía, verlo en €.

Un saludo y gracias de nuevo, Miguel Ángel.
