### ISSUE TITLE
El atributo Period no coincide

### ISSUE THREAD

**Issue by burguiss** [MiguelAngelLV/tarifa_20td#5]
He hecho una automatización y no consigo que funcione correctamente porque, creo, que el atributo Period no coincide con el periodo en el que estamos en algún tramo. El periodo punta lo marca como P1 de 10h a 14h y como P3 de 18h a 22h. 

¿Me pasa solo a mi?

**Comment by MiguelAngelLV** [comment]
Acabo de subir la actualización.

El P3 de 18 a 22h estaba mal como indicas, pero de 10 a 14h es P1, así eso estaba bien:

![image](https://github.com/MiguelAngelLV/tarifa_20td/assets/638110/1d0b24f4-2031-4d9e-b841-22c0efca774a)

**Comment by burguiss** [comment]
Ahora lo he visto en el código. Correcto, estaba mal el P3 de 18 a 22.

Gracias!

**Comment by MiguelAngelLV** [comment]
Espero que no haya habido muchos calentadores de agua dándolo todo en hora punta...

**Comment by burguiss** [comment]
Justo, eso mismo. Me he vuelto un poco loco cambiando varias vaces la automatización creyendo que lo había mirado mal...
