### ISSUE TITLE
Adaptación de tarifa 2.0 td a 3.0 TD

### ISSUE THREAD

**Issue by marioJR1979** [MiguelAngelLV/tarifa_20td#7]
Buenos días, Miguel Angel. 

Estoy usando Tarifa 2.0 TD para sacar los costes de nuestras instalaciones en tarifa 3.0 TD. En nuestro caso tenemos tarifa indexada con que añado el margen en cada periodo. El problema es que desvirtua la grafica de enrgía ya que por un lado pone el consumo con el precio PVPC y por otro lado otra vez el consumo con el margen. No sé si se te ocurre algo que pueda hacer para poder hacerlo aunque se que la tarifa 3.0TD por lo que quizá no se pueda hacer tan facilmente, pero quizá se te ocurra algo a ti para sin adaptar nada poder hacerlo.

Un saludo, gracias.

**Comment by MiguelAngelLV** [comment]
No te termino de entender la verdad. 

Ese margen que añades, ¿Cómo lo añades? ¿Añades dos veces el consumo en el panel de energía?

Si quieres crear una entidad nueva que sea la suma de dos, lo ideal es usar un Template: https://www.home-assistant.io/integrations/template/

¿Has probado a usar el componente PVPC? https://www.home-assistant.io/integrations/pvpc_hourly_pricing/

**Comment by marioJR1979** [comment]
También tengo otro problema, y es que en el coste fijo no me deja introducir valores mayores de 3 €/día y en la 3.0 TD los coste por día dependiendo de la tarifa pueden llegar a mucho más. En mi caso son casi 5 €/día por instalación ¿Podrías hacer algún cambio para poder adaptarlo?

Un saludo. Gracias.

**Comment by MiguelAngelLV** [comment]
> También tengo otro problema, y es que en el coste fijo no me deja introducir valores mayores de 3 €/día y en la 3.0 TD los coste por día dependiendo de la tarifa pueden llegar a mucho más. En mi caso son casi 5 €/día por instalación ¿Podrías hacer algún cambio para poder adaptarlo?
> 
> Un saludo. Gracias.

Eso sí puedo cambiártelo sin problema.

**Comment by MiguelAngelLV** [comment]
Ya tienes la versión 1.1.2 con el máximo a 10€.

**Comment by marioJR1979** [comment]
Jo.. que rapido eres. Gracias.

Si. efectivamente, añado dos veces el consumo en el panel de energía, No veo como hacerlo de otra manera. Tarifa 2.0 TD esta creado para tarifa fija. La diferencia con la tarifa 3.0 TD es que hay 6 periodos y dependiendo del més se usan unos u otros. En mi caso que es indexados se usa la PVPC más un margen con lo que solo tendría que añadir el margen ya que aunque hay 6 periodos solo se utilizan en indexado los 3 mismos de PVPC. Pero me falta el margen. Si añado el margen con un consumo por periodo, pues me crea las graficas como si tuviera el doble consumo. Por eso mi consulta, por si hay alguna posibilida de hacer algo. Que entiendo que no se pueda o se absurdo lo que te indico. 

Un saludo.

**Comment by MiguelAngelLV** [comment]
Pero si usas PVPC más un margen, debes usar el componente PVPC no el de Tarifa 2.0TD, porque cada día, cada hora, vas a tener un precio distinto.

Como te indicaba arriba, la forma de hacerlo es creando un sensor nuevo usando el componente template.

Básicamente, un template es una «fórmula»  donde indicas «quiero que al sensor patata le sumes 0.03» por ejemplo, y te crea un nuevo sensor dónde su valor será el de patata + 0.03.

**Comment by marioJR1979** [comment]
Me cabas de ilustrar, eso es lo que necesitaba que me dijeses. Voy a ello.

Muchas gracias.
