### ISSUE TITLE
Ampliacion del proyecto

### ISSUE THREAD

**Issue by javifly** [MiguelAngelLV/tarifa_20td#8]
Hola me he instalado este complemento en mi home assistnat y replica perfectamente mi tarifa añadiendo los precios de cada tramo. En ese sentido va perfecto.

Quería preguntar si se habia pensado en ir mas ayá de replicar los precios de tarifa y meter variables de almacenamiento de consumo diario, mensual, anual, calculo de gasto electrico diario, mensual y anual, etc...

Gracia

**Comment by MiguelAngelLV** [comment]
Ems... Todo eso lo hace ya Home Assistant en el Panel de Energía. Solo debes configurar como precio de consumo la entidad.

No sé muy bien que parte echas en falta.

**Comment by javifly** [comment]
Si, la tarifa la he configurado y va perfecta 🤩 pero a lo mejor es que no se usarlo… pero no veo los acumulados diarios o mensuales. Solo me los hace horarios. Y tampoco veo calculos monetarios de lo que cuesta la luz de forma diaria o mensual (teniendo en cuenta que el precio de la factura depende de la tarifa pero de cosas extra como en precio de la potencia, alquiler de contador, iva etc…

**Comment by MiguelAngelLV** [comment]
Tienes que ir a Ajustes -> Paneles de Control -> Energía.

En consumo pones algún medidor de consumo que tengas y en coste seleccionas «usar entidad precio actual» y seleccionas precio_luz..

Después creas otro consumo y seleccionas como medidor Costes Fijos, para costes una entidad que realiza un seguimiento de los costes totales seleccionando Costes Fijos Totales.

Y en el panel de Energía deberán salir todos tus consumos por hora, día, mes, semana... Lo que quieras. Pero claro, después de pasar horas, días, meses, semanas con todo configurado.

**Comment by MiguelAngelLV** [comment]
Tengo pendiente hacer un vídeo sobre cómo configurar todo esto correctamente (tengo un canal de Youtube de Home Assistant https://www.youtube.com/@lachozadigital)

**Comment by javifly** [comment]
q bueno! me dare una vuelta por tus videos, y si haces ese video sería estupendo claro!

**Comment by javifly** [comment]
> Tienes que ir a Ajustes -> Paneles de Control -> Energía.
> 
> En consumo pones algún medidor de consumo que tengas y en coste seleccionas «usar entidad precio actual» y seleccionas precio_kwh..
> 
> Después creas otro consumo y seleccionas como medidor Costes Fijos, para costes una entidad que realiza un seguimiento de los costes totales seleccionando Costes Fijos Totales.
> 
> Y en el panel de Energía deberán salir todos tus consumos por hora, día, mes, semana... Lo que quieras. Pero claro, después de pasar horas, días, meses, semanas con todo configurado.

Es decir, tendría que meter en costes fijos el precio de la potencia, del aqluiler de contador etc.. ¿no? Para sacar el coste fijo del día y sumarlo al del consumo. ¿no?

**Comment by MiguelAngelLV** [comment]
Sí. Todas esas partes fijas, las pones en el campo «Costes fijos». Se refiere al valor por día. Lo más sencillo es buscar la última factura, ver cuanto son todos los costes fijos y dividirlos por el número de días.

**Comment by javifly** [comment]
Si, justo es lo que he realizado, está super bien ahora, Casi clavo el importe de mi factura, solo faltan 2 cosillas. El impuesto electrico y el iva. Se te ocurre como gestionar esa parte?

**Comment by MiguelAngelLV** [comment]
La forma más sencilla es que los valores que pongas ya tengan eso calculado.

Ahora mismo tenemos un 0.5+5% si no recuerdo mal. Pues pon todos los valores (fijos y variables) multiplicados por 1.055

**Comment by javifly** [comment]
si, buena idea, o dejar el calculo sin impuestos o meter la todo multiplicado x el impuesto
