### ISSUE TITLE
La integración no provee entidades en HA 2023.11.2

### ISSUE THREAD

**Issue by ssorgatem** [MiguelAngelLV/tarifa_20td#9]
Desde la actualización ya no funciona:

![image](https://github.com/MiguelAngelLV/tarifa_20td/assets/108138/e8960531-c442-49fb-8305-01febc8bea1f)

**Comment by MiguelAngelLV** [comment]
¿Desde la actualización de HA o del componente?

Sería interesante si puedes ver en los registros si muestra algún error, porque a mí por ahora me está funcionando correctamente, por si es algún conflicto concreto.
